### ISSUE TITLE
[8h] Improvement of games

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/games#13]
Descrption:
finish the game with a positive and negative scenario

**Comment by a-matyukh** [comment]
Positive cases for 4 games added (Drakosha, Plane, Spaceship, Rastamasha)
https://github.com/easably/games/commit/87fea1ad0ff73362c4f5fee5912403f7e9542cd0
https://github.com/easably/games/commit/37b61da593257a7937a7c5b61dd9a42bc4f409f6
https://github.com/easably/games/commit/74b2c88e388e2f3b636f803e28aacfc86e57fcf4
https://github.com/easably/games/commit/0d1676f881850cdd33b818912062b9394a6ea6f2

**Comment by a-matyukh** [comment]
Finish callback for modal window in Tutor added
https://github.com/easably/games/commit/fbcdf448e9705f51273e45a25392dc3c07c2a226
https://github.com/easably/games/commit/4a64ee82311dc0d8d616b043a9ed216b85c96ac4
https://github.com/easably/games/commit/3cc3a6ad9d5e717af7b3c2be672617cbb7ca2fde
https://github.com/easably/games/commit/9e9321e80ff57125f7a658638242cc054767a66a
https://github.com/easably/games/commit/5c75c8c991f75e38ed04d080e1334517735156e7
https://github.com/easably/games/commit/4a84ca7bf5980d31a9e1a9efeca3ec76a9402ac1
https://github.com/easably/games/commit/dfb3978ee9592f94e82613d0b598b99d19ef3b05

**Comment by a-matyukh** [comment]
*For all games*
- [x] no intermediate state
- [x] no notification text
- [x] no public info inside game
https://github.com/easably/games/commit/052a9a6ec22880f98870a74484a235c3f2ff8c28

**1. Plane**
- [x] plane don’t up own nose at big speed
- [x] finish speed at all cases is one and only
https://github.com/easably/games/commit/84d22337465d4a5842b8fe1b5b9ef89966d00fe2

**2. Drakosha**
- [x] correct position of drakosha at last effort
https://github.com/easably/games/commit/7c71bae22313a47c91af0e9a6e5f6d0a8c0fb245

**3. Spaceship**
https://github.com/easably/games/commit/c7f69e53e72280e20c5385d9baca255c0482a73f

**Comment by a-matyukh** [comment]
**4. Dragon in Egypt**
- [x] positive and negative cases added
https://github.com/easably/games/commit/b4f2160405370c7f6a0d821d0d480fc95c31f8e5

**6. Rastamasha**
- [x] common requirements for games added
https://github.com/easably/games/commit/1c90b06f8cdfd505eeaf6e20c83310a06657417d

**7. Mummy**
- [x] positive cases added 
https://github.com/easably/games/commit/e87f4fd692d1e6a9e187442bf1bc222dd5577683

**9. Elephant**
- [x] positive and negative cases added
https://github.com/easably/games/commit/0a1f2109bf9f42a70101463b9f0dc1dbcd7e123b

**Comment by EugeneShastak** [comment]
4. Does not work correctly, (the dragon is not displayed during the game)
