### ISSUE TITLE
[8h] be in charge of R&D management

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/games#7]
Description:
you are engaged in R&D on managing a large map and along the way makes some kind of game in which the deterioration or improvement of the situation around the GG will be clearly seen with correct or incorrect answers

**Comment by a-matyukh** [comment]
Added two games as a result this research:
1. Rewrite on phaser with map old pixi game about space ship

<img width="554" alt="Screen Shot 2020-08-19 at 11 15 38" src="https://user-images.githubusercontent.com/20292939/90610146-b063bc80-e20d-11ea-924e-33abaa4a4504.png">

2. New game on phaser about dragon in Egypt

<img width="553" alt="Screen Shot 2020-08-19 at 11 16 04" src="https://user-images.githubusercontent.com/20292939/90610249-d38e6c00-e20d-11ea-9803-834f169c1a1e.png">
