### ISSUE TITLE
[16h] Prepare an interface prototype for product work

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/games#91]
## Components
- [x] translate the layout into components

## Streams
- [x] make a thread "Learning new words" in figma

## Analytics
Discuss analytics with Sveta and set metrics on the stream
- [x] retention
- [x] other target metrics

game involvement
- time on one game
- the number of words in the dictionary

resources available for sale
- premium account
- new words to dictionary
- ready set of words
link to monetization

**Comment by a-matyukh** [comment]
Startuem!
[Figma-board](https://www.figma.com/file/IfAi5eM7tzW3Zlq8ARawN2/eLang-Tutor-Interface?node-id=379%3A931) ready for product work
